### ISSUE TITLE
Re-registration of edgenode - Timeout & Objectsync error

### ISSUE THREAD

**Issue by hanneshoettinger** [kubeedge/kubeedge#1857]
**What happened**:
The edge device reboots and restarts the edgecore process. The edge node is not able to re-register again at cloudcore - stays NotReady. 
The node is able to re-register again, if I delete the objectsync deployment and re-deploy that again.
When I delete the node with kubectl, cloudcore still looks for the edgenode in the logs. 
Edgecore log:
`E0622 07:52:08.086418     804 edged_status.go:398] register node failed, error: timeout to get response
E0622 07:52:08.086768     804 edged_status.go:425] Register node failed: timeout to get response
`
**What you expected to happen**:
Cloudcore detects that the edgenode was already registered and successfully re-registers the device.

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):
KubeEdge 1.3.0
Cri-o 1.18

**CloudSide Environment**:
Ubuntu VM using microk8s

**Comment by GsssC** [comment]
this is a bug fix by #1670

**Comment by hanneshoettinger** [comment]
Thanks for the hint. 
I think this will solve the timeout issue.

Moreover, the objectsync seems to be another issue, where it happens that the edgenode connects again, but a deleted pod keeps running on the edge device, even tough it was deleted using kubectl. 
If I then re-deploy objectsync the pod is successfully deleted on the edgenode.

**Comment by GsssC** [comment]
> When I delete the node with kubectl, cloudcore still looks for the edgenode in the logs.

this is a bug because cloudcore has not yet collected garbage-objectsyncs which is created by delted node.And will be fixed by #1855.

> If I then re-deploy objectsync the pod is successfully deleted on the edgenode.
could tell me more details about `re-deploy objectsync`?

**Comment by fisherxu** [comment]
Thanks for pointing out :) The timeout issue now has been fixed.

> If I then re-deploy objectsync the pod is successfully deleted on the edgenode.

For the Objectsync error, can you add more details?

**Comment by fisherxu** [comment]
> When I delete the node with kubectl, cloudcore still looks for the edgenode in the logs.

When delete the node, is the edgecore process stopped in edgenode?

**Comment by hanneshoettinger** [comment]
@fisherxu the edgecore process is not stopped in the edgenode, as I would like to simulate a device running in the field. So the process should recover the node from the cloudside...

By objectsync I mean, that I delete the objectsync_v1alpha1.yaml and apply it again. (edgenode always running). Sometimes a restart of cloudcore also helps...it is hard to describe a scenario to reconstruct that issue, because it seems to happen only in special circumstances. The edge node stays NotReady, however, the Pods do not change state (running). This is also kind of confusing...

**Comment by GsssC** [comment]
@hanneshoettinger 
>  The edge node stays NotReady, however, the Pods do not change state (running).
In default situation, Pods will be evicted (controllered by controllerManager)after 5mins if edge node still stays in NotReaty. Within 5mins, because of no new podstatus update event recived from edgenode, it remains origin status.

BUT, it still does not explain why deleting objectsyncs could help delete pod in edgenode, and it is unreasonable. May It is caused by  combined bugs in v1.3.0.

**Comment by hanneshoettinger** [comment]
ok, haven't seen switching the pod to evicted in kubernetes master (have to test that again, but normally I waited more than 5mins).

Ok, need to clarify that: Deleting objectsyncs help to re-register the edgenode - to be able to switch to Ready status again in the kubernetes master. The edgenode is running and the pods are also running on the edge device. When I restart cloudcore it sometimes also work to re-register (re-connect) the edgenode. But if I delete then a running pod, the pod keeps running on the edgenode and only gets deleted if I re-deploy objectsync.

**Comment by s099064146** [comment]
@hanneshoettinger 
Could you please teach me how to delete objectsyncs (I mean some commands and steps which are necessary to solve this issue.)? Since I faced the same problem yesterday (2020/06/25), I am afraid of turning off my computers due to this issue.
I am a little bit frustrated with continuing to rebuild the  KubeEdge cluster with each reboot event.
Thank you in advance!

**Comment by fengyehong** [comment]
release 1.3.1 is also affeted by this issue, can we get 1.3.2 release soon?
