### ISSUE TITLE
how to configure prometheus to monitor edgenode in kubeedge via https?

### ISSUE THREAD

**Issue by OJumpyo** [kubeedge/kubeedge#3295]
**What happened and what you expected to happen**:
#### what happened: 
      1.  I have deployed a kubernetes group with 1 master node, 2 woker node and 2 edge node, by deploying kube-prometheus i have got the data from prometheus and viewed it on the Grafana. However, the metrics data on edge node I have not seen yet. 
      2. I have configured the **kubectl logs** and **Collect metrics from edge**  by following the guide at [kubeedge.io](https://v1-6.docs.kubeedge.io/en/docs/advanced/metrics/) and deployed the metrics-server successfully which i could use `kubectl logs` `kubectl top node/pod` to get the metrics data from all the nodes now.
      3.  when I apply node-exporter i get the error that shows `error cannot find service account in pod to build in-cluster rest config`
      4. I followed the guide u suggested in this issue #2092 to `configure edgecore to make it use CNI-plugin to create pod, add below:`
     
 ```yaml
         edgecore.yaml
//...
Modules:
    edged:
        networkPluginName: cni
//...
 ```

    but i don not know how to config the cni plugin to coonnect the k8s api-server **directly** since you have pointed out that it is very important. so could i ask where to find the guide to do it?
   by the way, my environment will show as below.
  
   i have read your talk about the metrics-server about depolying on kubeedge, and about the conversation of future works to do supporting CNI in edgecore and support users to monitor edgenode by with using prometheus directly not changing its default config. 
   could u plz show me some guidances or other information ? @s099064146  @Poor12 @GsssC 
   thank u very much in advance!

#### what i expect to happen:
    1. knowing the ans why  the kube-rbac-proxy cannot find service account thus it could not run well in edge node
    2.  **how to config the prometheus series of tools well in edgenode** , since i have seen ur changelog.md and i guess it may have implemented in the version v1.7.x series. so what i need to do configuring it well?
**How to reproduce it (as minimally and precisely as possible)**:
      applying the kube-prometheus series yaml of node-exporter-xxx -> link:<https://github.com/prometheus-operator/kube-prometheus/releases/tag/v0.6.0> and <https://github.com/prometheus-operator/kube-prometheus/tree/v0.6.0/manifests>
**Anything else we need to know?**:
    1.  i deployed the kubernetes with kubeadm and i deployed the kubeedge with binary, only a cloudcore and a edgecore in different node separately.
    2. in edge node, there is not kube-flannel or kube-proxy or anything else related to kubernetes.
**Environment**:
- Kubernetes version (use `kubectl version`):
   
~~~
    root@master:/# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
~~~

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

~~~
root@master:/# cloudcore --version
KubeEdge v1.6.2
~~~

~~~
root@edge1:~# /usr/local/bin/edgecore --version
2021-11-13 14:34:11.381139 I | INFO: Install client plugin, protocol: rest
2021-11-13 14:34:11.381402 I | INFO: Installed service discovery plugin: edge
KubeEdge v1.6.2
root@edge2:~# /usr/local/bin/edgecore --version
2021-11-13 06:35:15.143923 I | INFO: Install client plugin, protocol: rest
2021-11-13 06:35:15.144439 I | INFO: Installed service discovery plugin: edge
KubeEdge v1.6.2
~~~

**Comment by OJumpyo** [comment]
by the way, I have also tried to deploy the kube-flannel in edge node after changing edgecore.yaml's config using cni, but only to get error that the kube-flannel pod logs as belows.
~~~
root@master:~# kubectl get pod -n kube-system
NAME                                                                             READY   STATUS    RESTARTS   AGE
coredns-7ff77c879f-5g5lr                                               1/1     Running     11                308d
coredns-7ff77c879f-hlhkf                                               1/1     Running     11                308d
etcd-lab216-poweredge-r730                                        1/1     Running     11               308d
kube-apiserver-lab216-poweredge-r730                       1/1     Running     0          25d
kube-controller-manager-lab216-poweredge-r730      1/1     Running     25         308d
kube-flannel-ds-4wzsb                                                   0/1     Error          2          45s
kube-flannel-ds-jx4p9                                                    1/1     Running     0          74m
kube-flannel-ds-k85wn                                                  1/1     Running     0          74m
kube-flannel-ds-xpbbx                                                   0/1     Error          2           54s
kube-proxy-bz8d8                                                          1/1     Running    9          167d
kube-proxy-jmvtj                                                            1/1     Running    4          167d
kube-scheduler-lab216-poweredge-r730                      1/1     Running    27         241d
metrics-server-68c764c8fc-ctm7v                                  1/1     Running    0          46h

root@master:~# kubectl logs -f kube-flannel-ds-4wzsb -n kube-system
ERROR: logging before flag.Parse: I1113 06:58:28.875363       1 main.go:519] Determining IP address of default interface
ERROR: logging before flag.Parse: I1113 06:58:28.876747       1 main.go:532] Using interface with name enp2s0 and address 10.112.138.182
ERROR: logging before flag.Parse: I1113 06:58:28.876877       1 main.go:549] Defaulting external address to interface address (10.112.138.182)
W1113 06:58:28.877021       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W1113 06:58:28.877078       1 client_config.go:613] error creating inClusterConfig, falling back to default config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
ERROR: logging before flag.Parse: E1113 06:58:28.877619       1 main.go:250] Failed to create SubnetManager: fail to create kubernetes config: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

~~~

**Comment by OJumpyo** [comment]
in the past days, i have searched that we could monitor the edgenode with prometheus using its serviceMonitor to scrape metrics from metrics server, since kubeedge has provided metrics api with edgestream and cloudstream enabled to deliver its metrics. 
Now, what puzzles me is that how could i configure it to scrape the metrics from metrics-server via https?

i tried the streamCA.crt and stream.crt in /etc/kubeedge/ folder but not worked.  port 10003 or port 443 in metrics-server pod using kubeedge's crt & key files, am i right?

i am still not so familiar with kubeedge and prometheus, so any guidence would help me.

Thanks everyone in advance!

**Comment by OJumpyo** [comment]
having had a talk with kubeedge's engineer,  question solved. thanks @fisherxu . 

/close

**Comment by JotaCruz20** [comment]
Could you explain what you did to fix?

**Comment by siredmar** [comment]
@OJumpyo so what was the issue then? Would you mind telling us?

**Comment by OJumpyo** [comment]
Hi, sorry for not replying to the issue these days, the problem for me that time is that my master node is on the cloud while edge node behind the Operator's Intranet. I prefer they transmit messages through HTTPS protocol, so it is with the monitor data. But the version of Kubeedge 1.6.2 will throw an issue that the service account token cannot be get, which I use a Kube-Prometheus operator yaml to run them as pods and services in Kubernetes. The issue is fixed in the later version of Kubeedge, maybe v1.8 or 1.7. So you could run Kube-Prometheus in Kubeedge directly. For me, I just write a program and run it as a pod on the edge node to scrab some index data I need and follow the Kubeedge doc to transmit to the cloud for aggregation, a typical prometheus and grafana usage.

**Comment by mhh12121** [comment]
In latest v1.12.1 version, It seems that the above error still cannot be correctly resolved

```
W1113 06:58:28.877078       1 client_config.go:613] error creating inClusterConfig, falling back to default config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
```
owing to this image `kube-rbac-proxy`  cannot run on edge side;

A temp resolution is to use `push` method to collect edge side metrics (pushgateway);

Hope that anyone could find a better way...

**Comment by YinanTsao** [comment]
> In latest v1.12.1 version, It seems that the above error still cannot be correctly resolved
> 
> ```
> W1113 06:58:28.877078       1 client_config.go:613] error creating inClusterConfig, falling back to default config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
> ```
> 
> owing to this image `kube-rbac-proxy` cannot run on edge side;
> 
> A temp resolution is to use `push` method to collect edge side metrics (pushgateway);
> 
> Hope that anyone could find a better way...

Hi @mhh12121, I am not having the same problem but mine is similar. The node-exporter pods could get into CLBO status after getting deployed on the edge node with 1/2, which is wired.
Did this ever happen to you?

**Comment by mhh12121** [comment]
> > In latest v1.12.1 version, It seems that the above error still cannot be correctly resolved
> > ```
> > W1113 06:58:28.877078       1 client_config.go:613] error creating inClusterConfig, falling back to default config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
> > ```
> > 
> > 
> > owing to this image `kube-rbac-proxy` cannot run on edge side;
> > A temp resolution is to use `push` method to collect edge side metrics (pushgateway);
> > Hope that anyone could find a better way...
> 
> Hi @mhh12121, I am not having the same problem but mine is similar. The node-exporter pods could get into CLBO status after getting deployed on the edge node with 1/2, which is wired. Did this ever happen to you?

It's wat I mentioned above. The reason why u saw 1/2 is that kube-rbac-proxy cannot get certificate in edge node(it does not save certificate at all); You could dive into the log by `kubectl logs ` to see if it's the same issue;
