### ISSUE TITLE
can't DeviceTwin data in cloud

### ISSUE THREAD

**Issue by kuangren1984** [kubeedge/kubeedge#6430]
**What happened**:
kubectl get  devices.devices.kubeedge.io modbus-rtsim-instance -o yaml
can't get the status.twin info

<img width="3568" height="1600" alt="Image" src="https://github.com/user-attachments/assets/da130eb0-9f65-424b-852c-b6c6378b25bc" />

<img width="835" height="766" alt="Image" src="https://github.com/user-attachments/assets/e665e3bf-0d8c-4d89-a232-dc0d31b51452" />

**What you expected to happen**:
show the status.twin.holding-register-30.reported value

**How to reproduce it (as minimally and precisely as possible)**:

<img width="1780" height="214" alt="Image" src="https://github.com/user-attachments/assets/931300e0-9ab9-4d57-9e80-8e8bf8ccd795" />
modbus Mappper code is this :https://github.com/kubeedge/mappers-go/pull/113/files#diff-f92660821e3f07f47af8cc558f607b8a8d1d9955b3ffc21f68c5ec2c4ded1345

because the mapper just support modbus rtu;
so I add some code to support modbus tcp in driver.go

<img width="2551" height="1720" alt="Image" src="https://github.com/user-attachments/assets/cfaa2be3-9486-4fe0-852c-54f0440c665f" />

kubectl apply  -f Device.yaml
kubectl apply -f modbus-mapper-deployment.yaml

journalctl -u edgecore -f 
have some error:

<img width="3787" height="256" alt="Image" src="https://github.com/user-attachments/assets/6f060db0-fbb4-456e-90ec-5e3cc3968b7d" />

but actually , we can get mqtt message from the cmd:

<img width="1912" height="169" alt="Image" src="https://github.com/user-attachments/assets/0d69fccd-513f-40bd-983b-1b801213afe3" />

so ,why?

**Anything else we need to know?**:
one : the DeviceModel.yaml is:

<img width="1072" height="562" alt="Image" src="https://github.com/user-attachments/assets/36c75c55-f063-4b8b-93ee-e23fc2304108" />

the Device.yaml is:

<img width="1120" height="1405" alt="Image" src="https://github.com/user-attachments/assets/2ddd6cf5-5ead-497a-81f9-2b5ba2525ad4" />

<img width="1006" height="769" alt="Image" src="https://github.com/user-attachments/assets/a3812776-d84d-48b4-8634-89f21ea7522d" />

the modbus-mapper-deployment.yaml is:

<img width="1339" height="1663" alt="Image" src="https://github.com/user-attachments/assets/db8ff920-34b2-49bc-a93f-b5424ca56568" />

<img width="1711" height="700" alt="Image" src="https://github.com/user-attachments/assets/2e6214a5-fa5b-4d0c-b33f-2a62683509b6" />

**Environment**:
- Kubernetes version (use `kubectl version`):1.30
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.21
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):Rocky Linux release 9.4 (Blue Onyx)
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by kuangren1984** [comment]
I add some log in the source code (devicetwin.go);
and get the logs as below:
crictl logs -f 5d65473ead7ee

<img width="3781" height="1408" alt="Image" src="https://github.com/user-attachments/assets/6274c3ce-049b-4630-a76a-240707bffeac" />

**Comment by wbc6080** [comment]
> $hw/events/device//modbus-rtsim-instance/twin/update

The message reported by the device in edgecore is incorrect, it should be $hw/events/device/default/modbus-rtsim-instance/twin/update . In other words, the device namespace was not reported, resulting in a parsing error. 

This seems to be a bug fixed in v1.16, and the mapper you are using is v1.15. You can use the latest [mapper-framework](https://github.com/kubeedge/mapper-framework/tree/release-1.21) to generate a new mapper project, and then copy the device driver code of the current mapper to the new mapper, which should solve this problem.

**Comment by kuangren1984** [comment]
OK!
Many thanks!
I will try your suggestion!

**Comment by kuangren1984** [comment]
I tried the mapper-framework 1.16 ,
it's still failed;
the log of the cmd "journalctl -u edgecore -f" is:

<img width="3325" height="637" alt="Image" src="https://github.com/user-attachments/assets/f47e4167-7af8-4e98-88e9-2ce202868827" />

**Comment by wbc6080** [comment]
> I tried the mapper-framework 1.16 , it's still failed; the log of the cmd "journalctl -u edgecore -f" is:

 Maybe I remembered the bug fix time wrongly, but I tried the latest 1.21 version and it is correct. You can use this version

**Comment by kuangren1984** [comment]
OK,I will try the latest 1.21 version;
Thank you！

**Comment by kuangren1984** [comment]
> > I tried the mapper-framework 1.16 , it's still failed; the log of the cmd "journalctl -u edgecore -f" is:
> 
> Maybe I remembered the bug fix time wrongly, but I tried the latest 1.21 version and it is correct. You can use this version

@wbc6080 ，if the framework use the latest 1.21;
the modbus mapper is correct ?when I  still use the link as below:
https://github.com/https://github.com/kubeedge/mappers-go/pull/113/files#diff-f92660821e3f07f47af8cc558f607b8a8d1d9955b3ffc21f68c5ec2c4ded1345

**Comment by wbc6080** [comment]
These sample mappers are built based on the mapper-framework and then filled with the device driver code (driver directory). So the correct approach is firstly use the 1.21 version of the mapper-framework to build the mapper project, and then copy the device driver code in the link to the generated mapper project. You can refet to https://kubeedge.io/docs/developer/mappers/#how-to-create-your-own-mappers

**Comment by kuangren1984** [comment]
first, I used the 1.21 version of the mapper-framework to build the mapper project;
and then copy the device driver code and  add the devicestatus.go code to the generated mapper project；

but the error is still exist:

1、the cmd "crictl logs -f 729c53467815d" is :

<img width="3060" height="351" alt="Image" src="https://github.com/user-attachments/assets/73fca9ed-3c14-41c7-b8d0-e4cecbbd8707" />
2、the cmd "journalctl -u edgecore -f" is:

<img width="3228" height="627" alt="Image" src="https://github.com/user-attachments/assets/79474d05-e0e3-48ba-aabd-289af0922547" />
3、the Device.yaml

<img width="1077" height="1701" alt="Image" src="https://github.com/user-attachments/assets/904755dd-737b-4d10-a558-a1ae408ba2ab" />

<img width="1040" height="416" alt="Image" src="https://github.com/user-attachments/assets/f5184b1a-52f2-48d3-83fd-df8ff02ce43e" />
4、the cluster info:

<img width="1779" height="230" alt="Image" src="https://github.com/user-attachments/assets/da09c71a-7d56-455c-9411-f7f44ebc033e" />

@wbc6080 ,it's confused, what's the problem?
